### ISSUE TITLE
Client Update

### ISSUE THREAD

**Issue by LordLozz** [IamSanjid/pokeone-pluse#6]
looking for the new api for the client update that is valid on 12/24/2019 or a release to the .dll that i can update for the latest client.

**Comment by IamSanjid** [comment]
Did you mean PSXAPI.DLL and MAPAPI.DLL?

**Comment by LordLozz** [comment]
Yes

**Comment by IamSanjid** [comment]
Then grab https://github.com/Perfare/Il2CppDumper/ and grab PokeOne's APK version and dump all the members of those DLLs

**Comment by juninhooo266** [comment]
i got the new DLLs and yet, it is giving an error when i try to compile it
